version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - .:/usr/app
    links:
      - mongo
      - redis

  jobs:
    container_name: workers
    build: .
    command: yarn persistencia
    volumes:
      - .:/usr/app
    links:
      - redis

  mongo:
    container_name: mongoDB_dev
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis_dev
    image: redis
    volumes:
      - ./data:/redis/db
    ports:
      - "6379:6379"
